//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFaceDownloader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FaceArrayPic.jpg")]
        public string strUsrTargetFile {
            get {
                return ((string)(this["strUsrTargetFile"]));
            }
            set {
                this["strUsrTargetFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123")]
        public string textUsrCropFaceStartX {
            get {
                return ((string)(this["textUsrCropFaceStartX"]));
            }
            set {
                this["textUsrCropFaceStartX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62")]
        public string textUsrCropFaceStartY {
            get {
                return ((string)(this["textUsrCropFaceStartY"]));
            }
            set {
                this["textUsrCropFaceStartY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("778")]
        public string textUsrCropFaceWidth {
            get {
                return ((string)(this["textUsrCropFaceWidth"]));
            }
            set {
                this["textUsrCropFaceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public string textUsrCropFaceHeight {
            get {
                return ((string)(this["textUsrCropFaceHeight"]));
            }
            set {
                this["textUsrCropFaceHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public string textUsrFaceResizeWidth {
            get {
                return ((string)(this["textUsrFaceResizeWidth"]));
            }
            set {
                this["textUsrFaceResizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public string textUsrFaceReSizeHeight {
            get {
                return ((string)(this["textUsrFaceReSizeHeight"]));
            }
            set {
                this["textUsrFaceReSizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public string textUsrFaceArrayNumHeri {
            get {
                return ((string)(this["textUsrFaceArrayNumHeri"]));
            }
            set {
                this["textUsrFaceArrayNumHeri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string textUsrFaceArrayNumVert {
            get {
                return ((string)(this["textUsrFaceArrayNumVert"]));
            }
            set {
                this["textUsrFaceArrayNumVert"] = value;
            }
        }
    }
}
